#!/bin/sh
#
# Copyright (c) 2019-present Sonatype, Inc. All rights reserved.
# Includes the third-party code listed at http://links.sonatype.com/products/nexus/attributions.
# "Sonatype" is a trademark of Sonatype, Inc.
#
LIFECYCLE_CLI_PKG=com.sonatype.insight.brain.cli
LIFECYCLE_RESULTS_FILE=lifecycle-results.txt

mkdir -p ${LIFECYCLE_OUT}
java -cp ${SONATYPE_LIB}/docker-nexus-iq-cli.jar ${LIFECYCLE_CLI_PKG}.NexusPolicyEvaluator $@ 2>&1 | tee ${LIFECYCLE_OUT}/${LIFECYCLE_RESULTS_FILE}
#java -cp ${SONATYPE_LIB}/docker-nexus-iq-cli.jar ${LIFECYCLE_CLI_PKG}.PolicyEvaluationResultsProcessor $@ --results ${LIFECYCLE_BIN}/${LIFECYCLE_RESULTS_FILE}
