#!/bin/sh
#
# Copyright (c) 2019-present Sonatype, Inc. All rights reserved.
# Includes the third-party code listed at http://links.sonatype.com/products/nexus/attributions.
# "Sonatype" is a trademark of Sonatype, Inc.
#
SONATYPE_OUT_DIR=${SONATYPE_DIR}/out
SONATYPE_CLI_PKG=com.sonatype.insight.brain.cli
SONATYPE_RESULTS_FILE=results.json

mkdir -p ${SONATYPE_OUT_DIR}
java -cp ${SONATYPE_LIB}/docker-nexus-iq-cli.jar ${SONATYPE_CLI_PKG}.NexusPolicyEvaluator $@ -r ${SONATYPE_OUT_DIR}/${SONATYPE_RESULTS_FILE} 2>&1
java -cp ${SONATYPE_LIB}/docker-nexus-iq-cli.jar ${SONATYPE_CLI_PKG}.PolicyEvaluationResultsProcessor -r ${SONATYPE_OUT_DIR}/${SONATYPE_RESULTS_FILE}
